[variables]
NODE_OPTIONS = '--max-old-space-size=4096'
HOSTNAME = '0.0.0.0'

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'node .next/standalone/server.js'
